export const inventory = [
  {
    id: 1,
    material: "Cement",
    category: "Construction",
    site: "Green Valley - Site A",
    project: "Green Valley Residency",
    quantity: 350,
    unit: "Bags",
    minimumStock: 500,
    status: "Low Stock",
    lastUpdated: "07 Sep 2026",
  },
  {
    id: 2,
    material: "Steel",
    category: "Construction",
    site: "Green Valley - Site A",
    project: "Green Valley Residency",
    quantity: 18,
    unit: "Tons",
    minimumStock: 10,
    status: "Available",
    lastUpdated: "06 Sep 2026",
  },
  {
    id: 3,
    material: "Bricks",
    category: "Construction",
    site: "Green Valley - Site A",
    project: "Green Valley Residency",
    quantity: 15000,
    unit: "Pieces",
    minimumStock: 8000,
    status: "Available",
    lastUpdated: "05 Sep 2026",
  },
  {
    id: 4,
    material: "Cement",
    category: "Construction",
    site: "Metro Heights - Main Site",
    project: "Metro Heights",
    quantity: 250,
    unit: "Bags",
    minimumStock: 400,
    status: "Low Stock",
    lastUpdated: "07 Sep 2026",
  },
  {
    id: 5,
    material: "Bricks",
    category: "Construction",
    site: "Metro Heights - Main Site",
    project: "Metro Heights",
    quantity: 15000,
    unit: "Pieces",
    minimumStock: 8000,
    status: "Available",
    lastUpdated: "04 Sep 2026",
  },
  {
    id: 6,
    material: "Cement",
    category: "Construction",
    site: "Palm Residency - Site A",
    project: "Palm Residency",
    quantity: 180,
    unit: "Bags",
    minimumStock: 350,
    status: "Low Stock",
    lastUpdated: "07 Sep 2026",
  },
  {
    id: 7,
    material: "Steel",
    category: "Construction",
    site: "Palm Residency - Site A",
    project: "Palm Residency",
    quantity: 8,
    unit: "Tons",
    minimumStock: 5,
    status: "Available",
    lastUpdated: "06 Sep 2026",
  },
  {
    id: 8,
    material: "Sand",
    category: "Construction",
    site: "Green Valley - Site A",
    project: "Green Valley Residency",
    quantity: 45,
    unit: "Tons",
    minimumStock: 20,
    status: "Available",
    lastUpdated: "05 Sep 2026",
  },
];

export const materialMovements = [
  {
    id: 1,
    material: "Cement",
    site: "Green Valley - Site A",
    type: "Received",
    quantity: 200,
    unit: "Bags",
    date: "07 Sep 2026",
  },
  {
    id: 2,
    material: "Steel",
    site: "Green Valley - Site A",
    type: "Issued",
    quantity: 5,
    unit: "Tons",
    date: "06 Sep 2026",
  },
  {
    id: 3,
    material: "Bricks",
    site: "Metro Heights - Main Site",
    type: "Received",
    quantity: 5000,
    unit: "Pieces",
    date: "05 Sep 2026",
  },
  {
    id: 4,
    material: "Cement",
    site: "Palm Residency - Site A",
    type: "Issued",
    quantity: 70,
    unit: "Bags",
    date: "05 Sep 2026",
  },
];
